export const SET_LOADED_SUBJECTS_CHILDREN = 'Subject.SET_LOADED_SUBJECTS_CHILDREN';
export const SET_LOADED_SUBJECTS_ROOT = 'Subject.SET_LOADED_SUBJECTS_ROOT';
export const CLEAR_ACTIVE = 'Subject.CLEAR_ACTIVE';
export const CLEAR_CONTENT = 'Subject.CLEAR_CONTENT';
export const CLEAR = 'Subject.CLEAR';